#!/usr/bin/perl -slan
# Expects output from nowtss.
# Breaks up output with a break line after every day.
# If -w is given, breaks up every week.

BEGIN { my %report = (); my $date; my $new_date; }

$new_date = $w? `date -jf %F $F[0] +%U`: $F[0];
if ($date && $date ne $new_date) {
  print '';
}
print;
$date = $new_date;

END { print ''; }
