#!/usr/bin/perl -sln

# Given a list of timestamps and tasks, 
# ts1 [estimate] task1
# ts2 estimate2 task2
# ts3 task3

# We want to print the elapsed times, so that all the information on an entry is on the same line.
# ts1 (ts2-ts1)/est task1
# ts2 (ts3-ts2)/est task2
# ts3 (now-ts3)/est ask3

# est = est (if one is given) | '' (empty space)
BEGIN {
  $t1 = 0;
  $t2 = 0;
  #$line = '';
  sub print_line {
    #print "\n$line";
    if (($date, $time, $est, $task) = $line =~ /([\d\-]+)\s+([\d\:]+)\s+([\d\.]*\s*)\b(.*)$/) {
      #print "date $date, time $time, est $est, task $task";
      my $est = $est eq ''? '': sprintf("%.02f", $est);
      my $act = sprintf("%.02f", ($t2 - $t1) / 3600); 
      #print "t1: $t1; t2: $t2; act: $act";
      print "$date $time $act/$est $task"
    }
  }
}

if (($date, $time, $est, $task) = $_ =~ /([\d\-]+) ([\d\:]+)/) {
  $t2 = `date -jf '%F %T' "$date $time" '+%s' 2> /dev/null`;
  chomp($t2);
  &print_line if $line;
  $t1 = $t2;
  $line = $_;
} 
#else {
#  print "Not in good form: $_\n";
#}

END {
  $t2 = `date -j '+%s' 2> /dev/null`; # use the current time
  chomp($t2);
  &print_line();
}

__END__



